# Generated by Django 2.2.4 on 2019-10-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191010_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='file',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
