"""
Django settings for indosat_b2b project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5@&6ei-%#fba^4w5m0q#^q@opihebt00*5rrcs959*-td+@+_e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'core',
    # 'admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'indosat_b2b.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'indosat_b2b.context_processors.global_template_vars',
            ],
        },
    },
]

WSGI_APPLICATION = 'indosat_b2b.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = 'staticfiles'
STATIC_URL = '/static/'
AUTH_USER_MODEL = 'core.User'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'core:index'

PKL_CACHE_DIR = os.path.join(BASE_DIR, 'pkl_cache')

PKL_FILENAMES = dict(
    links_df='links.pkl',
    closed_tickets_df='closed_ticket.pkl',
    open_tickets_df='open_ticket.pkl',
)

EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"

HIERARCHY_LEVEL_NAMES = ['SALES_NAME', 'AVP', 'VP', 'SVP', 'N/A', 'N/A']
HIERARCHY_SHEET_NAME = 'SALES HIERARCHY'

SHEET_NAMES = dict(
    links_df='ASSET MIDI LINKS',
    closed_tickets_df='CLOSED TICKET',
    open_tickets_df = 'IN PROGRESS TICKET',
)

COLUMN_NAMES = dict(
    service_id='SERVICE_ID',
)

import django_heroku

django_heroku.settings(locals())
#
# if 'DATABASE_URL' in os.environ:
#     import dj_database_url
#
#     DATABASES = {'default': dj_database_url.config()}

DEFAULT_PASSWORD = os.getenv('DEFAULT_PASSWORD', '123')

SALES_DASHBOARD_URL = 'https://www.google.com'